apply plugin: 'groovy'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    implementation gradleApi()//gradle sdk
    implementation localGroovy()//groovy sdk
    compileOnly "com.android.tools.build:gradle:8.8.0"
    implementation 'org.javassist:javassist:3.30.2-GA'
    // https://mvnrepository.com/artifact/org.jooq/joor-java-6
    implementation 'org.jooq:joor-java-8:0.9.15'
}